### ISSUE TITLE
Advision Criteria

### ISSUE THREAD

**Issue by Nefari0uss** [OSUOSC/constitution#8]
The document states that the adviser term is 1 year. Perhaps add language suggesting that the term may be freely renewed upon majority consent of the officers?

My spelling mistakes are to be ignored.

**Comment by Nefari0uss** [comment]
Updates? @moore3071 @oslerw @kriegersaurusrex

**Comment by notori0us** [comment]
I have a comment related to all this--

Let's try to avoid adding things to the constitution unless they really are explicitly required to be there. Reading the preamble, it's as if our original founders wanted as little bureaucracy as possible.

**Comment by moore3071** [comment]
Late night misreading of the constitution says @Nefari0uss. Closing this specific issue.
